[project]
name = "pastel-tati"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=2.1.0",
    "django>=4.2.0",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.9",
    "python-decouple>=3.8",
]
